### ISSUE TITLE
Add an `autoupdate` tag to created PRs

### ISSUE THREAD

**Issue by simonbray** [planemo-autoupdate/autoupdate#1]
Not sure how, it isn't supported by gh as far as I can tell. Also the bot would need to be given the necessary permissions on target repos.

**Comment by simonbray** [comment]
Actually I think you can make custom API calls with `gh api ...`

**Comment by simonbray** [comment]
Oh it's way easier than I thought: `gh pr create --title 'Test' --body 'Test' --label 'tool-autoupdate'`

@bgruening could you maybe give @planemo-autoupdate permissions to add tags on the compchem and bgruening repos, so we can try this out?

**Comment by bgruening** [comment]
For ogranisations that seems to be ok. There is a triage role that could be used, but for normal repos I need to make the bot commiter afaik. Not sure if all people want that. Can we make this optional?

**Comment by simonbray** [comment]
> Can we make this optional?

Yes - so far I was implementing it as a separate CI action for each repo. So it is fully customisable.

**Comment by simonbray** [comment]
fixed in https://github.com/planemo-autoupdate/autoupdate/commit/fb668d769aed63f665e97bbdeb2e7511e5808d1b
