### ISSUE TITLE
Autoupdate is failing on bgruening

### ISSUE THREAD

**Issue by lldelisle** [planemo-autoupdate/autoupdate#29]
I guess because before it was another 'user' that was writting the PR, @bgruening you need to close PRs or give more access to the bot.
GraphQL: gxydevbot does not have the correct permissions to execute `UpdatePullRequest` (updatePullRequest)
https://github.com/planemo-autoupdate/autoupdate/actions/runs/6845552206/job/18621744391#step:9:257

**Comment by nsoranzo** [comment]
Yes, the new gxydevbot user can push commits to open PR branches but cannot change the PR title.
If the old PRs are mass-closed, the bot won't reopen them unless there is a newer release than the one in the closed PR.

**Comment by lldelisle** [comment]
Ah yes, good point... Then I guess the best option would be to (temporarily?) give more power to gxydevbot, no?
